version: '3.8'
services:
  ai_kassa_db:
    image: postgres:latest
    container_name: ai_kassa_db
    volumes:
      - /var/lib/postgresql/data2:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - '${DB_PORT}:5432'