"""add_dish_table

Revision ID: ae3ea9c670b5
Revises: 7b8f8a688d20
Create Date: 2024-10-16 07:25:06.360959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae3ea9c670b5'
down_revision: Union[str, None] = '7b8f8a688d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('code_name', sa.String(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('count_type', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('changing_dish_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changing_dish_id'], ['changing_dish_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dish_table')
    # ### end Alembic commands ###
