"""add_changing_dish_table

Revision ID: 7b8f8a688d20
Revises: eac9f94211b0
Create Date: 2024-10-15 08:27:36.622210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b8f8a688d20'
down_revision: Union[str, None] = 'eac9f94211b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changing_dish_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('menu_table', sa.Column('ai_model_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_table', 'ai_model_name')
    op.drop_table('changing_dish_table')
    # ### end Alembic commands ###
