"""add_week_day_dish_table

Revision ID: 2dad26e9223a
Revises: 05b1aa063ebe
Create Date: 2024-10-22 06:24:04.789215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dad26e9223a'
down_revision: Union[str, None] = '05b1aa063ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_day_dish_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('changing_dish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['changing_dish_id'], ['changing_dish_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dish_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('changing_dish_table', sa.Column('strategy', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('changing_dish_table', 'strategy')
    op.drop_table('week_day_dish_table')
    # ### end Alembic commands ###
