"""add_history_table

Revision ID: 5ff0fa515bbe
Revises: eb9aac6c95bc
Create Date: 2025-02-11 20:12:29.255674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff0fa515bbe'
down_revision: Union[str, None] = 'eb9aac6c95bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('kassa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['kassa_id'], ['kassa_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_table')
    # ### end Alembic commands ###
