"""add_password

Revision ID: 63a1c56350e2
Revises: 218e1b4064c1
Create Date: 2025-10-25 12:06:52.466176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a1c56350e2'
down_revision: Union[str, None] = '218e1b4064c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers_table', sa.Column('password', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers_table', 'password')
    # ### end Alembic commands ###
