"""add_discount_transaction_table

Revision ID: fa728ae74853
Revises: 5ff0fa515bbe
Create Date: 2025-02-11 20:40:14.711051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa728ae74853'
down_revision: Union[str, None] = '5ff0fa515bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_transaction_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('way', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount_transaction_table')
    # ### end Alembic commands ###
