"""add_r_keeper_dish_table

Revision ID: fd7c91bd5571
Revises: ed88e62b7b7b
Create Date: 2025-01-26 17:35:09.620474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7c91bd5571'
down_revision: Union[str, None] = 'ed88e62b7b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_keeper_dish_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dish_id'], ['dish_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_keeper_dish_table')
    # ### end Alembic commands ###
