"""add_kassa_table

Revision ID: eb9aac6c95bc
Revises: d60f8af0f57b
Create Date: 2025-02-11 19:54:22.845105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9aac6c95bc'
down_revision: Union[str, None] = 'd60f8af0f57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kassa_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('food_point_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_point_id'], ['food_point_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kassa_table')
    # ### end Alembic commands ###
