"""add_category_table

Revision ID: 218e1b4064c1
Revises: bf75c8f45274
Create Date: 2025-10-24 16:19:22.064382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218e1b4064c1'
down_revision: Union[str, None] = 'bf75c8f45274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('dish_table', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dish_table', 'categories_table', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish_table', type_='foreignkey')
    op.drop_column('dish_table', 'category_id')
    op.drop_table('categories_table')
    # ### end Alembic commands ###
