"""add_org_and_iiko_menu

Revision ID: 2a0152d75cf2
Revises: 5e79535714e4
Create Date: 2025-10-22 18:54:53.912128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0152d75cf2'
down_revision: Union[str, None] = '5e79535714e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iiko_credentials_table', sa.Column('organization_id', sa.String(), nullable=True))
    op.add_column('iiko_credentials_table', sa.Column('iiko_menu_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iiko_credentials_table', 'iiko_menu_id')
    op.drop_column('iiko_credentials_table', 'organization_id')
    # ### end Alembic commands ###
