"""add_iiko_id

Revision ID: bf75c8f45274
Revises: adc2b651a6a8
Create Date: 2025-10-22 19:35:07.570050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf75c8f45274'
down_revision: Union[str, None] = 'adc2b651a6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iiko_dishes_table', sa.Column('iiko_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iiko_dishes_table', 'iiko_id')
    # ### end Alembic commands ###
