"""add_iiko_terminals

Revision ID: a2e1bdbbb011
Revises: 2a0152d75cf2
Create Date: 2025-10-22 19:08:45.656679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e1bdbbb011'
down_revision: Union[str, None] = '2a0152d75cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iiko_terminals_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('terminal_id', sa.String(), nullable=False),
    sa.Column('kassa_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['kassa_id'], ['kassa_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kassa_id'),
    sa.UniqueConstraint('terminal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iiko_terminals_table')
    # ### end Alembic commands ###
