"""add_iiko_dishes

Revision ID: adc2b651a6a8
Revises: a2e1bdbbb011
Create Date: 2025-10-22 19:28:14.676692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc2b651a6a8'
down_revision: Union[str, None] = 'a2e1bdbbb011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iiko_dishes_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dish_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iiko_dishes_table')
    # ### end Alembic commands ###
