"""add_r_keeper_id

Revision ID: afa1b38b3604
Revises: 7103c22ea10c
Create Date: 2025-02-20 19:21:03.814205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa1b38b3604'
down_revision: Union[str, None] = '7103c22ea10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('r_keeper_dish_table', sa.Column('r_keeper_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('r_keeper_dish_table', 'r_keeper_id')
    # ### end Alembic commands ###
